### PR TITLE
Feature 6: Chef Mode

### LINKED ISSUE #6: Feature 6: Chef Mode

### PR DESCRIPTION
**Pull request by ActualX**
Closes #6

### CODE REVIEW

**Review by lukekrikorian — APPROVED** [review]
Looks good to me!

**Review by shape-warrior-t — COMMENTED** [review]
Some comments and questions:
- Aside from ingredients and steps, are we planning to also have tools, tags, etc in this use case? I find it weird that we have ingredients but not tools or tags; either we can make all of that other info into a separate thing, or we should incorporate it all into this use case.
- Stylistically, I think `showIngredients` is a bit of a weird name for a method that returns the ingredient list as a string without printing to screen. And the documentation summary being identical to `getIngredients` doesn't help make things more clear. Maybe something like `getIngredientsAsString` would work better, with the documentation summary being "Returns the recipe's ingredients in string form" or something? Just a suggestion, it's up to you whether you want to change it.
- What is the plan if `showNextStep` is called multiple times after there are no more steps? It seems like the step counter will continue to increase. Are we planning to forbid this through the UI?

**Comment by lukekrikorian** [comment]
> * Aside from ingredients and steps, are we planning to also have tools, tags, etc in this use case? I find it weird that we have ingredients but not tools or tags; either we can make all of that other info into a separate thing, or we should incorporate it all into this use case.

I think a point can be made for including tools in the initial display of ingredients but I'm not sure tags need to be shown in chef mode.

**Comment by jasala10** [comment]
Everything looks good!

**Review by jasala10 — APPROVED** [review]

**Pull request merged**
