### PR TITLE
Clean up code

### PR DESCRIPTION
**Pull request by lukekrikorian**
* Renames RecipeManager to RecipeInteractor and moves it to a new folder (suggestion from Milestone 4 grading)
* Adds missing documentation to Database
* Adds a new PersistenceError exception to Database (suggestion from Milestone 4 grading)
* Adds missing documentation to operations
* Removes duplicate getPreparationItem methods from tag, ingredient, and tool
* Adds documentation to RecipePreparationItems

See #40

### CODE REVIEW

**Comment by shape-warrior-t** [comment]
I might've just been misunderstanding the feedback, but I though the `PersistenceError` thing was about replacing _all_ instances of `SQLException` throughout the use case layer with something less specific to SQL?

**Comment by lukekrikorian** [comment]
SQLExceptions aren't thrown from any use-case except the DataConverter. All use-cases are converting SQLExceptions thrown by the DAO, the throwing signature of which we can't change without making a (technically very complicated) DAO proxy. The de facto standard in use-cases is to convert any SQLExceptions thrown by DAOs into RuntimeExceptions. This is sub-optimal, but at least this conversion to PersistenceError changes the dependency where we can.

**Comment by shape-warrior-t** [comment]
...Alright then.

**Review by shape-warrior-t — APPROVED** [review]

**Comment by Selenarn** [comment]
If we rename RecipeManager to RecipeInteractor, then we have to change other files that contain the import recipeManager, right?

**Review by Selenarn — APPROVED** [review]
Looks good to me.  It seems we do change the name for all the files that contain RecipeManager.

**Pull request merged**
